# Generated by Django 4.0.1 on 2022-03-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=20)),
                ('employee_contact', models.IntegerField()),
                ('employee_image', models.ImageField(upload_to='profile_images/')),
                ('employee_cnic', models.IntegerField()),
                ('employee_email', models.EmailField(max_length=254, verbose_name='enter you email')),
                ('employee_address', models.CharField(max_length=200)),
                ('employee_gender', models.CharField(max_length=10)),
                ('employee_dob', models.DateField(null=True)),
                ('employee_age', models.IntegerField()),
                ('employee_blood_group', models.CharField(max_length=10)),
                ('employee_type', models.CharField(max_length=30)),
                ('employee_pay', models.IntegerField(default=0)),
                ('employee_username', models.CharField(max_length=20)),
                ('employee_password', models.CharField(default='0000', max_length=20)),
                ('employee_status', models.CharField(max_length=20)),
            ],
        ),
    ]
