# Generated by Django 4.0.1 on 2022-02-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecord',
            name='employee_pay',
            field=models.IntegerField(default=0),
        ),
    ]
