# Generated by Django 3.2 on 2022-03-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecord',
            name='super_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_cnic',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_contact',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='enter you email'),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_password',
            field=models.CharField(default='0000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
