# Generated by Django 3.2 on 2022-03-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20220325_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerecord',
            name='employee_password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
