# Generated by Django 4.0.1 on 2022-02-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_remove_employeerecord_employee_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerecord',
            name='employee_password',
            field=models.CharField(default='0000', max_length=20),
        ),
    ]
