# Generated by Django 4.0.1 on 2022-03-02 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='snookerIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('attened_by', models.CharField(default='user', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='snookerTableIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('table_number', models.CharField(max_length=10)),
                ('minutes_per_table', models.IntegerField()),
                ('snooker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snooker.snookerincome')),
            ],
        ),
    ]
