# Generated by Django 3.2 on 2022-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snooker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snookerincome',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
