# Generated by Django 3.2 on 2022-02-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snooker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snookertableincome',
            name='table_number',
            field=models.CharField(max_length=10),
        ),
    ]
