# Generated by Django 3.2 on 2022-04-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeerecord_employee_password'),
        ('snooker', '0002_alter_snookerincome_attened_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snookerincome',
            name='attened_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snooker_attened_by', to='employees.employeerecord'),
        ),
    ]
