# Generated by Django 3.2 on 2022-04-19 11:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('cnic_no', models.CharField(max_length=15, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('shop_no', models.CharField(max_length=20)),
                ('electric_bill', models.CharField(max_length=30, null=True)),
                ('gas_bill', models.CharField(max_length=30, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('payment_status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='rentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=25)),
                ('rent_pay_date', models.DateField()),
                ('rent_duration', models.CharField(max_length=25)),
                ('total_rent', models.IntegerField()),
                ('rent_end_date', models.DateField()),
                ('rent_pay_by', models.CharField(max_length=50)),
                ('payment_gas_bill', models.BooleanField(null=True)),
                ('payment_electric_bill', models.BooleanField(null=True)),
                ('payment_created_at', models.DateField(default=datetime.datetime.now)),
                ('rent_payment_attended_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_payment_attended_by', to='employees.employeerecord')),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_id', to='rental.rentaldata')),
            ],
        ),
        migrations.AddField(
            model_name='rentaldata',
            name='active_rent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_rent_id', to='rental.rentalpayment'),
        ),
        migrations.AddField(
            model_name='rentaldata',
            name='rent_attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rent_attended_by', to='employees.employeerecord'),
        ),
    ]
