# Generated by Django 4.0.1 on 2022-03-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.IntegerField()),
                ('item_name', models.CharField(max_length=50)),
                ('item_unit', models.CharField(max_length=30)),
                ('item_category', models.CharField(max_length=30)),
                ('item_brand', models.CharField(max_length=30)),
                ('item_manufacturer', models.CharField(max_length=30)),
                ('item_selling_price', models.IntegerField()),
                ('item_max_selling_quantity', models.IntegerField()),
                ('item_min_selling_quantity', models.IntegerField()),
                ('item_reorder_level', models.IntegerField()),
                ('item_image', models.ImageField(upload_to='items_images/')),
                ('item_expire_date', models.DateField()),
                ('item_description', models.CharField(max_length=100)),
                ('item_status', models.CharField(max_length=20)),
                ('item_expiry_day', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NonStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nonStock_item_code', models.IntegerField()),
                ('nonStock_item_name', models.CharField(max_length=50)),
                ('nonStock_item_unit', models.CharField(max_length=30)),
                ('nonStock_item_category', models.CharField(max_length=30)),
                ('nonStock_item_brand', models.CharField(max_length=30)),
                ('nonStock_item_manufacturer', models.CharField(max_length=30)),
                ('nonStock_item_selling_price', models.IntegerField()),
                ('nonStock_item_max_selling_quantity', models.IntegerField()),
                ('nonStock_item_min_selling_quantity', models.IntegerField()),
                ('nonStock_item_image', models.ImageField(upload_to='items_images/')),
                ('nonStock_item_expire_date', models.DateField()),
                ('nonStock_item_description', models.CharField(max_length=100)),
                ('nonStock_item_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=50)),
                ('product_unit', models.CharField(max_length=30)),
                ('product_category', models.CharField(max_length=30)),
                ('product_brand', models.CharField(max_length=30)),
                ('product_manufacturer', models.CharField(max_length=30)),
                ('product_selling_price', models.IntegerField()),
                ('product_max_selling_quantity', models.IntegerField()),
                ('product_min_selling_quantity', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='items_images/')),
                ('product_description', models.CharField(max_length=100)),
                ('product_status', models.CharField(max_length=20)),
            ],
        ),
    ]
