# Generated by Django 4.0.1 on 2022-04-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_account', models.CharField(max_length=50)),
                ('supplier_name', models.CharField(max_length=50)),
                ('supplier_contact', models.IntegerField()),
                ('supplier_email', models.CharField(max_length=50)),
                ('supplier_status', models.CharField(max_length=20)),
                ('supplier_address', models.CharField(max_length=200)),
                ('supplier_city', models.CharField(max_length=50)),
                ('supplier_country', models.CharField(max_length=50)),
            ],
        ),
    ]
