# Generated by Django 4.0.1 on 2022-03-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonstock',
            name='nonStock_item_purchase_price',
            field=models.IntegerField(default=0),
        ),
    ]
