# Generated by Django 4.0.1 on 2022-03-03 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_nonstock_nonstock_item_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='item_expire_date',
        ),
        migrations.RemoveField(
            model_name='nonstock',
            name='nonStock_item_expire_date',
        ),
    ]
