# Generated by Django 4.0.1 on 2022-03-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_remove_items_item_expire_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_unit_price', models.IntegerField()),
                ('inventory_unit_tax', models.IntegerField()),
                ('inventory_purchased_quantity', models.IntegerField()),
                ('inventory_sub_total', models.IntegerField()),
                ('inventory_tax_total', models.IntegerField()),
                ('inventory_item_total', models.IntegerField()),
                ('inventory_reference_number', models.IntegerField()),
                ('inventory_expiry_date', models.DateField()),
                ('inventory_stock_in_shop', models.IntegerField()),
                ('inventory_stock_in_storeroom', models.IntegerField()),
                ('inventory_item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_code', to='cafeteria.items')),
                ('inventory_item_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_name', to='cafeteria.items')),
                ('inventory_item_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_item_unit', to='cafeteria.items')),
                ('inventory_unit_net_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_net_price', to='cafeteria.items')),
            ],
        ),
    ]
