# Generated by Django 3.2 on 2022-02-28 14:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=25)),
                ('meridiem', models.CharField(max_length=5)),
                ('booking_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('captain_name', models.CharField(max_length=25)),
                ('contact_number', models.IntegerField()),
                ('team_attended_by', models.CharField(max_length=25)),
                ('member_created_at', models.DateField(default=datetime.datetime(2022, 2, 28, 19, 39, 34, 324967))),
                ('member_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2022, 2, 28, 19, 39, 34, 325988))),
                ('fee', models.IntegerField()),
                ('paid', models.CharField(default='Unpaid', max_length=10)),
                ('booking_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_time', to='futsal.booking')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='futsal.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='futsal.team')),
            ],
        ),
    ]
