# Generated by Django 3.2 on 2022-02-21 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=25)),
                ('captain_name', models.CharField(max_length=25)),
                ('contact_number', models.IntegerField()),
                ('team_attended_by', models.CharField(max_length=25)),
                ('member_created_at', models.DateField(default=datetime.datetime(2022, 2, 21, 18, 27, 16, 242298))),
                ('member_updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
