# Generated by Django 4.0.1 on 2022-04-02 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeerecord_employee_password'),
        ('futsal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_attended_by', to='employees.employeerecord'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_attended_by', to='employees.employeerecord'),
        ),
    ]
