# Generated by Django 4.0.1 on 2022-03-01 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0002_auto_20220228_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 20, 47, 3, 32074)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 1, 20, 47, 3, 31075)),
        ),
    ]
