# Generated by Django 4.0.1 on 2022-04-02 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employeerecord_employee_password'),
        ('futsal', '0002_match_match_attended_by_alter_team_team_attended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_attended_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employeerecord'),
        ),
    ]
