# Generated by Django 4.0.1 on 2022-02-25 13:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_alter_team_member_created_at_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=25)),
                ('meridiem', models.CharField(max_length=5)),
                ('booking_date', models.DateField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='match',
            name='data',
        ),
        migrations.RemoveField(
            model_name='match',
            name='meridiem',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 18, 42, 24, 75016)),
        ),
        migrations.AlterField(
            model_name='match',
            name='paid',
            field=models.CharField(default='Unpaid', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 18, 42, 24, 74021)),
        ),
        migrations.AddField(
            model_name='match',
            name='booking_time',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='booking_time', to='futsal.booking'),
        ),
    ]
