# Generated by Django 3.2 on 2022-02-25 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_alter_team_member_created_at_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 16, 39, 1, 628924)),
        ),
    ]
