# Generated by Django 4.0.1 on 2022-03-02 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0003_alter_match_date_alter_team_member_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 14, 56, 2, 518682)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 14, 56, 2, 518682)),
        ),
    ]
