# Generated by Django 3.2 on 2022-02-25 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_alter_team_member_created_at'),
        ('futsal', '0004_booking_remove_match_data_remove_match_meridiem_and_more'),
    ]

    operations = [
    ]
