# Generated by Django 3.2 on 2022-03-02 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0004_alter_match_date_alter_team_member_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 19, 26, 47, 592676)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 19, 26, 47, 590683)),
        ),
    ]
