# Generated by Django 4.0.1 on 2022-02-26 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0005_merge_20220225_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 26, 16, 32, 29, 460339)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 26, 16, 32, 29, 459343)),
        ),
    ]
