# Generated by Django 3.2 on 2022-03-02 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futsal', '0006_auto_20220302_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 19, 39, 27, 109115)),
        ),
        migrations.AlterField(
            model_name='team',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 3, 2, 19, 39, 27, 107120)),
        ),
    ]
