# Generated by Django 4.0.1 on 2022-03-30 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField()),
                ('cnic_no', models.CharField(max_length=15, null=True)),
                ('reference', models.CharField(max_length=100, null=True)),
                ('shop_no', models.CharField(max_length=20)),
                ('electric_bill', models.CharField(max_length=30, null=True)),
                ('gas_bill', models.CharField(max_length=30, null=True)),
                ('rent_amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=25)),
                ('rent_pay_date', models.DateField()),
                ('rent_duration', models.CharField(max_length=25)),
                ('total_rent', models.IntegerField()),
                ('rent_end_date', models.DateField()),
                ('payment_status', models.CharField(max_length=150)),
                ('rent_pay_to', models.CharField(max_length=50)),
                ('rent_pay_by', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
