# Generated by Django 4.0.1 on 2022-03-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldata',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
