# Generated by Django 4.0.1 on 2022-03-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldata',
            name='cnic_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rentaldata',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rentaldata',
            name='electric_bill',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentaldata',
            name='gas_bill',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rentaldata',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
