# Generated by Django 4.0.1 on 2022-03-30 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_rentaldata_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldata',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
