# Generated by Django 4.0.1 on 2022-04-01 12:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_rentaldata_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentaldata',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='rentaldata',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='rentaldata',
            name='rent_amount',
        ),
        migrations.RemoveField(
            model_name='rentaldata',
            name='rent_duration',
        ),
        migrations.RemoveField(
            model_name='rentaldata',
            name='rent_end_date',
        ),
        migrations.RemoveField(
            model_name='rentaldata',
            name='rent_pay_date',
        ),
        migrations.RemoveField(
            model_name='rentaldata',
            name='total_rent',
        ),
        migrations.CreateModel(
            name='rentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_amount', models.IntegerField()),
                ('payment_mode', models.CharField(max_length=25)),
                ('rent_pay_date', models.DateField()),
                ('rent_duration', models.CharField(max_length=25)),
                ('total_rent', models.IntegerField()),
                ('rent_end_date', models.DateField()),
                ('payment_status', models.CharField(max_length=150)),
                ('payment_created_at', models.DateField(default=datetime.datetime.now)),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.rentaldata')),
            ],
        ),
    ]
