# Generated by Django 4.0.1 on 2022-03-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_rename_rent_end_data_rentaldata_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentaldata',
            name='shop_no',
            field=models.CharField(max_length=20),
        ),
    ]
