# Generated by Django 4.0.1 on 2022-04-02 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_rentaldata_payment_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalpayment',
            name='rental_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_id', to='accounting.rentaldata'),
        ),
    ]
