# Generated by Django 4.0.1 on 2022-02-12 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=25)),
                ('member_father_name', models.CharField(max_length=25)),
                ('member_cnic', models.CharField(max_length=13)),
                ('member_contact', models.IntegerField(max_length=11)),
                ('member_emergency_contact', models.IntegerField(max_length=11)),
                ('member_email', models.EmailField(max_length=254)),
                ('member_occupation', models.CharField(max_length=25)),
                ('member_address', models.CharField(max_length=255)),
                ('member_gender', models.CharField(max_length=10)),
                ('member_dob', models.DateField()),
                ('member_age', models.IntegerField()),
                ('member_blood_group', models.CharField(max_length=4)),
                ('member_height', models.CharField(max_length=5)),
                ('member_weight', models.IntegerField()),
                ('member_card_id', models.CharField(max_length=20)),
                ('member_target', models.CharField(max_length=100)),
                ('member_membership_expiry_date', models.DateField(default=datetime.datetime(2022, 2, 12, 14, 58, 40, 338791))),
                ('member_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('member_created_at', models.DateField(default=datetime.datetime(2022, 2, 12, 14, 58, 40, 338791))),
                ('member_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
                ('category_class', models.CharField(max_length=20)),
                ('category_months', models.CharField(max_length=15)),
                ('category_fee', models.IntegerField()),
                ('category_gender', models.CharField(max_length=15)),
                ('category_created_at', models.DateField(default=datetime.datetime(2022, 2, 12, 14, 58, 40, 338791))),
                ('category_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.FloatField()),
                ('payment_discount', models.FloatField()),
                ('payment_payable', models.FloatField()),
                ('payment_paid', models.FloatField()),
                ('payment_remaining', models.FloatField()),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_created_at', models.DateField(default=datetime.datetime(2022, 2, 12, 14, 58, 40, 339832))),
                ('payment_updated_at', models.DateField(auto_now=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='member_membership_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.membershipcategory'),
        ),
        migrations.CreateModel(
            name='BodyAssesments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neck', models.CharField(max_length=20)),
                ('shoulder', models.CharField(max_length=20)),
                ('chest_extended', models.CharField(max_length=20)),
                ('chest_normal', models.CharField(max_length=20)),
                ('forearms', models.CharField(max_length=20)),
                ('biceps', models.CharField(max_length=20)),
                ('wrist', models.CharField(max_length=20)),
                ('upper_abs', models.CharField(max_length=20)),
                ('lower_abs', models.CharField(max_length=20)),
                ('waist', models.CharField(max_length=20)),
                ('hip', models.CharField(max_length=20)),
                ('thigh', models.CharField(max_length=20)),
                ('calves', models.CharField(max_length=20)),
                ('ankles', models.CharField(max_length=20)),
                ('body_fat', models.CharField(max_length=20)),
                ('vascular', models.CharField(max_length=20)),
                ('medical_issue', models.CharField(max_length=40)),
                ('body_target', models.CharField(max_length=30)),
                ('assesment_date', models.DateTimeField(auto_now_add=True)),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.member')),
            ],
        ),
    ]
