# Generated by Django 3.2 on 2022-02-12 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 12, 19, 52, 45, 47430)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_membership_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 12, 19, 52, 45, 47430)),
        ),
        migrations.AlterField(
            model_name='membershipcategory',
            name='category_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 12, 19, 52, 45, 37331)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 12, 19, 52, 45, 47430)),
        ),
    ]
