# Generated by Django 4.0.1 on 2022-02-15 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20220215_1430'),
        ('theme', '0006_alter_member_member_created_at_and_more'),
    ]

    operations = [
    ]
