# Generated by Django 4.0.1 on 2022-02-15 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_merge_20220216_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 0, 51, 15, 135274)),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_membership_expiry_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 0, 51, 15, 135274)),
        ),
        migrations.AlterField(
            model_name='membershipcategory',
            name='category_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 0, 51, 15, 134277)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_created_at',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 0, 51, 15, 136274)),
        ),
    ]
